/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppCases {}
  interface AppDashboard {}
  interface AppHome {}
  interface AppNav {
    'componentName': string;
  }
  interface AppNewcase {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
}

declare global {


  interface HTMLAppCasesElement extends Components.AppCases, HTMLStencilElement {}
  var HTMLAppCasesElement: {
    prototype: HTMLAppCasesElement;
    new (): HTMLAppCasesElement;
  };

  interface HTMLAppDashboardElement extends Components.AppDashboard, HTMLStencilElement {}
  var HTMLAppDashboardElement: {
    prototype: HTMLAppDashboardElement;
    new (): HTMLAppDashboardElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {}
  var HTMLAppNavElement: {
    prototype: HTMLAppNavElement;
    new (): HTMLAppNavElement;
  };

  interface HTMLAppNewcaseElement extends Components.AppNewcase, HTMLStencilElement {}
  var HTMLAppNewcaseElement: {
    prototype: HTMLAppNewcaseElement;
    new (): HTMLAppNewcaseElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-cases': HTMLAppCasesElement;
    'app-dashboard': HTMLAppDashboardElement;
    'app-home': HTMLAppHomeElement;
    'app-nav': HTMLAppNavElement;
    'app-newcase': HTMLAppNewcaseElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppCases {
    'onDashboardEvent'?: (event: CustomEvent<any>) => void;
  }
  interface AppDashboard {
    'onDashboardEvent'?: (event: CustomEvent<any>) => void;
  }
  interface AppHome {}
  interface AppNav {
    'componentName'?: string;
  }
  interface AppNewcase {
    'onDashboardEvent'?: (event: CustomEvent<any>) => void;
  }
  interface AppProfile {
    'match'?: MatchResults;
  }
  interface AppRoot {}

  interface IntrinsicElements {
    'app-cases': AppCases;
    'app-dashboard': AppDashboard;
    'app-home': AppHome;
    'app-nav': AppNav;
    'app-newcase': AppNewcase;
    'app-profile': AppProfile;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-cases': LocalJSX.AppCases & JSXBase.HTMLAttributes<HTMLAppCasesElement>;
      'app-dashboard': LocalJSX.AppDashboard & JSXBase.HTMLAttributes<HTMLAppDashboardElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-nav': LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
      'app-newcase': LocalJSX.AppNewcase & JSXBase.HTMLAttributes<HTMLAppNewcaseElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


